presubmits:
  - name: presubmit-nephio-go-test
    decorate: true
    run_if_changed: "(\\.go|Makefile)$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - make
        args:
        - unit
  - name: presubmit-porch-e2e
    decorate: true
    optional: true
    run_if_changed: "(\\.go|Makefile)$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - make
        args:
        - test-porch
